# Generated by Django 4.2.29 on 2026-03-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, null=True)),
                ('address_line2', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('attorney_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('attorney_type', models.CharField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attorney',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('case_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, null=True)),
                ('case_title', models.CharField(blank=True, null=True)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('case_status', models.CharField(blank=True, null=True)),
                ('case_filed_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('disposition_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('disposition_status', models.CharField(blank=True, null=True)),
                ('disposition_status_date', models.DateField(blank=True, null=True)),
                ('disposition_code', models.CharField(blank=True, null=True)),
                ('disposition_date', models.DateField(blank=True, null=True)),
                ('judge', models.CharField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disposition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('docket_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('docket_date', models.DateField(blank=True, null=True)),
                ('docket_text', models.TextField(blank=True, null=True)),
                ('docket_currency', models.CharField(blank=True, null=True)),
                ('docket_amount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('docket_balance', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_start_time', models.DateTimeField(blank=True, null=True)),
                ('event_end_time', models.DateTimeField(blank=True, null=True)),
                ('event_judge', models.CharField(blank=True, null=True)),
                ('event_courtroom', models.CharField(blank=True, null=True)),
                ('event_result', models.CharField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('party_type', models.CharField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'party',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawCases',
            fields=[
                ('case_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField()),
                ('case_title', models.CharField(blank=True, null=True)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('case_status', models.CharField(blank=True, null=True)),
                ('case_filed_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, null=True)),
                ('first_party_name', models.CharField(blank=True, null=True)),
                ('first_party_type', models.CharField(blank=True, null=True)),
                ('first_attorney_name', models.CharField(blank=True, null=True)),
                ('first_attorney_type', models.CharField(blank=True, null=True)),
                ('first_event_start', models.DateTimeField(blank=True, null=True)),
                ('first_event_end', models.DateTimeField(blank=True, null=True)),
                ('first_event_judge', models.CharField(blank=True, null=True)),
                ('parties', models.JSONField(blank=True, null=True)),
                ('attorneys', models.JSONField(blank=True, null=True)),
                ('events', models.JSONField(blank=True, null=True)),
                ('docket', models.JSONField(blank=True, null=True)),
                ('dispositions', models.JSONField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='courtdata_django.cases')),
            ],
            options={
                'db_table': 'case_party',
                'managed': False,
            },
        ),
    ]
