# Generated by Django 4.2.29 on 2026-03-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtdata_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='attorney',
            options={},
        ),
        migrations.AlterModelOptions(
            name='caseparty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cases',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disposition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='docket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rawcases',
            options={},
        ),
    ]
