"""describe change

Revision ID: 30e795db3e52
Revises: 
Create Date: 2025-12-01 15:18:23.698110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30e795db3e52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.BigInteger(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('cases',
    sa.Column('case_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('case_title', sa.String(), nullable=True),
    sa.Column('case_description', sa.Text(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_filed_date', sa.Date(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('raw_cases',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('case_title', sa.String(), nullable=True),
    sa.Column('case_description', sa.Text(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_filed_date', sa.Date(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('first_party_name', sa.String(), nullable=True),
    sa.Column('first_party_type', sa.String(), nullable=True),
    sa.Column('first_attorney_name', sa.String(), nullable=True),
    sa.Column('first_attorney_type', sa.String(), nullable=True),
    sa.Column('first_event_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('first_event_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('first_event_judge', sa.String(), nullable=True),
    sa.Column('parties', sa.JSON(), nullable=True),
    sa.Column('attorneys', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('docket', sa.JSON(), nullable=True),
    sa.Column('dispositions', sa.JSON(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('disposition',
    sa.Column('disposition_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('disposition_status', sa.String(), nullable=True),
    sa.Column('disposition_status_date', sa.Date(), nullable=True),
    sa.Column('disposition_code', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('disposition_id')
    )
    op.create_table('docket',
    sa.Column('docket_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('docket_date', sa.Date(), nullable=True),
    sa.Column('docket_text', sa.Text(), nullable=True),
    sa.Column('docket_currency', sa.String(), nullable=True),
    sa.Column('docket_amount', sa.Numeric(), nullable=True),
    sa.Column('docket_balance', sa.Numeric(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('docket_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('event_end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('event_judge', sa.String(), nullable=True),
    sa.Column('event_courtroom', sa.String(), nullable=True),
    sa.Column('event_result', sa.String(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('party',
    sa.Column('party_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('address_id', sa.BigInteger(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('party_id')
    )
    op.create_table('attorney',
    sa.Column('attorney_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=True),
    sa.Column('attorney_type', sa.String(), nullable=True),
    sa.Column('address_id', sa.BigInteger(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.party_id'], ),
    sa.PrimaryKeyConstraint('attorney_id')
    )
    op.create_table('case_party',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.party_id'], ),
    sa.PrimaryKeyConstraint('case_id', 'party_id')
    )
    op.drop_table('raw_case_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_case_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parsed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='raw_case_data_pkey'),
    sa.UniqueConstraint('file_name', name='raw_case_data_file_name_key')
    )
    op.drop_table('case_party')
    op.drop_table('attorney')
    op.drop_table('party')
    op.drop_table('events')
    op.drop_table('docket')
    op.drop_table('disposition')
    op.drop_table('raw_cases')
    op.drop_table('cases')
    op.drop_table('address')
    # ### end Alembic commands ###
